kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./dev/kind/
    containerPath: /files
  - hostPath: ./dev/certs/padlok
    containerPath: /webhook-certs
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
          authentication-token-webhook-config-file: /files/webhook-config.yaml
          authentication-token-webhook-version: v1
        extraVolumes:
          - name: authn-webhook-files
            hostPath: "/files"
            mountPath: "/files"
            readOnly: true
          - name: authn-webhook-certs
            hostPath: "/webhook-certs"
            mountPath: "/webhook-certs"
            readOnly: true
