apiVersion: v1
kind: Config

clusters:
- cluster:
    server: https://padlok:6443/authenticate
    certificate-authority: /webhook-certs/cert.pem
  name: remote-authn

users:
- name: apiserver

current-context: webhook
contexts:
- context:
    cluster: remote-authn
    user: apiserver
  name: webhook
